#!/bin/bash
# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# This script automates the protobuf roll process described in
# third_party/protobuf/README.chromium.

set -euo pipefail

# Ensure we are executing from the root of the git repository.
REPO_ROOT=$(git rev-parse --show-toplevel 2>/dev/null) || {
  echo "Error: This script must be run from within the openscreen git repository."
  exit 1
}
cd "$REPO_ROOT"

# Verify we are in the openscreen repo by checking for third_party/protobuf.
if [[ ! -d "third_party/protobuf" ]]; then
  echo "Error: Could not find third_party/protobuf. Are you in the openscreen repository?"
  exit 1
fi

# Verify that the index is clean, to avoid wiping out existing local changes.
if ! git diff --quiet HEAD; then
  echo "Error: You have uncommitted changes. Please commit or stash them before rolling."
  exit 1
fi

CURRENT_VERSION=$(grep "^Version: " third_party/protobuf/README.chromium | awk '{print $2}' || true)
CURRENT_REVISION=$(grep "^Revision: " third_party/protobuf/README.chromium | awk '{print $2}' || true)

BUILD_DIR="out/Default"

while getopts ":C:" opt; do
  case ${opt} in
  C)
    BUILD_DIR=$OPTARG
    ;;
  \?)
    echo "Invalid Option: -$OPTARG" 1>&2
    exit 1
    ;;
  :)
    echo "Invalid Option: -$OPTARG requires an argument" 1>&2
    exit 1
    ;;
  esac
done
shift $((OPTIND - 1))

if [[ $# -ne 1 ]]; then
  echo "Current protobuf version: ${CURRENT_VERSION:-Unknown} (Revision: ${CURRENT_REVISION:-Unknown})"
  echo ""
  echo "Usage: $0 [-C <build_dir>] <version>"
  echo "Example: $0 -C out/Debug 33.1"
  echo ""
  echo "  -C <build_dir> : Specify the build directory. Defaults to 'out/Default'."
  echo ""
  echo "You MUST specify a target version. Rolling to an arbitrary new version (e.g. 34.1)"
  echo "without manually updating the patches/ directory will likely result in patch failures."
  echo ""
  echo "Recent potential upgrades (from GitHub tags):"
  # Fetch tags matching v[0-9]+.[0-9]+*, sort version numbers, and grab the last 10
  git ls-remote --tags https://github.com/protocolbuffers/protobuf.git |
    grep -oE 'refs/tags/v[0-9]+\.[0-9]+(\.[0-9]+)?$' |
    sed 's|refs/tags/v||' |
    sort -V | tail -n 10 |
    awk '{print "  - " $1}'
  exit 1
fi

VERSION="$1"

echo "Fetching revision for v${VERSION}..."
REVISION=$(git ls-remote https://github.com/protocolbuffers/protobuf.git "tags/v${VERSION}^{}" | cut -f1)

if [[ -z "${REVISION}" ]]; then
  echo "Error: Could not find git revision for tag v${VERSION}."
  exit 1
fi
echo "Target Revision: ${REVISION}"

echo "1. Identifying current protobuf version..."

if [[ -z "${CURRENT_VERSION}" || -z "${CURRENT_REVISION}" ]]; then
  echo "Error: Could not determine current version/revision from README.chromium"
  exit 1
fi

echo "Current Version: ${CURRENT_VERSION}"
echo "Rolling from ${CURRENT_VERSION} -> ${VERSION}"

echo "2. Nuking third_party/protobuf from orbit..."
rm -rf third_party/protobuf

echo "3. Downloading and extracting v${VERSION} release..."
TMP_DIR=$(mktemp -d)
trap 'rm -rf "$TMP_DIR"; echo "Removed temporary directory..."' EXIT
mkdir -p third_party/protobuf
curl -sL "https://github.com/protocolbuffers/protobuf/archive/refs/tags/v${VERSION}.tar.gz" -o "${TMP_DIR}/protobuf-${VERSION}.tar.gz"
tar -xzf "${TMP_DIR}/protobuf-${VERSION}.tar.gz" -C third_party/protobuf --strip-components=1

echo "3a. Pruning unused language bindings and build systems..."
pushd third_party/protobuf >/dev/null
rm -rf .github/ bazel/ csharp/ java/ objectivec/ php/ ruby/ rust/
popd >/dev/null

echo "4. Restoring OpenScreen/Chromium specific files..."
# Restore the files from the HEAD of the tree
git checkout HEAD -- \
  third_party/protobuf/BUILD.gn \
  third_party/protobuf/DEPS \
  third_party/protobuf/DIR_METADATA \
  third_party/protobuf/OWNERS \
  third_party/protobuf/README.chromium \
  third_party/protobuf/gen_extra_chromium_files.py \
  third_party/protobuf/proto_library.gni \
  third_party/protobuf/proto_sources.gni \
  third_party/protobuf/patches/

# Remove compatibility directory to fix CheckForTooLargeFiles presubmit
rm -rf third_party/protobuf/compatibility

echo "5. Applying patches..."
pushd third_party/protobuf >/dev/null
for patch in patches/*.patch; do
  echo "Applying $patch..."
  patch -s -p1 <"$patch" || {
    echo "Patch $patch failed to apply!"
    exit 1
  }
done
popd >/dev/null

# Clean up any backup files generated by patch
find third_party/protobuf -name "*.orig" -type f -delete

echo "6. Generating descriptor_pb2.py and plugin_pb2.py..."
pushd third_party/protobuf >/dev/null
./gen_extra_chromium_files.py -C ../../"${BUILD_DIR}"
popd >/dev/null

echo "7. Skipping bazel generation for Python edition defaults..."
echo "  Note: OpenScreen only links C++ protobuf, so we intentionally skip bazel here to avoid rules_go incompatibilities."
# To satisfy ninja which might require python_edition_defaults.py, we touch it.
mkdir -p third_party/protobuf/python/google/protobuf/internal
touch third_party/protobuf/python/google/protobuf/internal/python_edition_defaults.py

echo "8. Updating version identifiers..."
# We use perl for cross-platform in-place editing compatibility.
perl -pi -e "s/${CURRENT_VERSION}/${VERSION}/g" third_party/protobuf/README.chromium
perl -pi -e "s/${CURRENT_REVISION}/${REVISION}/g" third_party/protobuf/README.chromium

perl -pi -e "s/${CURRENT_VERSION}/${VERSION}/g" third_party/protobuf/version.json
perl -pi -e "s/${CURRENT_VERSION}/${VERSION}/g" third_party/protobuf/protobuf_version.bzl
perl -pi -e "s/${CURRENT_VERSION}/${VERSION}/g" third_party/protobuf/python/google/protobuf/__init__.py

echo "9. Validating patches against README.chromium..."
README_PATCHES=$(grep -E '^- [0-9]{4}-.*\.patch$' third_party/protobuf/README.chromium | sed 's/^- //' | sort || true)
LOCAL_PATCHES=$(ls third_party/protobuf/patches/*.patch 2>/dev/null | xargs -n 1 basename | sort || true)

MISSING_IN_README=$(comm -13 <(echo "$README_PATCHES") <(echo "$LOCAL_PATCHES"))
MISSING_ON_DISK=$(comm -23 <(echo "$README_PATCHES") <(echo "$LOCAL_PATCHES"))

if [[ -n "$MISSING_IN_README" || -n "$MISSING_ON_DISK" ]]; then
  echo "ERROR: Patch validation failed! README.chromium patch list does not match patches/ directory."
  if [[ -n "$MISSING_IN_README" ]]; then
    echo "The following patches exist in patches/ but are missing from README.chromium:"
    echo "$MISSING_IN_README"
  fi
  if [[ -n "$MISSING_ON_DISK" ]]; then
    echo "The following patches are listed in README.chromium but do not exist in patches/:"
    echo "$MISSING_ON_DISK"
  fi
  exit 1
fi
echo "Patch validation passed successfully."

echo "Roll complete!"
